import type { Restaurant } from '../types/restaurant';

// ⚠️ MOCK FUNCTION — هتتستبدل بـ GET /vendors لما الـ backend يخلص
export async function getRestaurants(): Promise<Restaurant[]> {
  await new Promise((resolve) => setTimeout(resolve, 400));

  return [
    {
      id: 'r1',
      name: 'Fresh Bowl & Co.',
      imageUrl: '/src/assets/images/restaurant-1.jpg',
      logoUrl: '/src/assets/images/logo-1.jpg',
      cuisineTags: ['Healthy', 'Poke', 'Salads'],
      rating: 4.8,
      reviewCount: 500,
      deliveryTimeMinutes: '20-30',
      deliveryFee: 2.99,
      isOpen: true,
    },
    {
      id: 'r2',
      name: 'Burger Joint',
      imageUrl: '/src/assets/images/restaurant-2.jpg',
      logoUrl: '/src/assets/images/logo-2.jpg',
      cuisineTags: ['American', 'Burgers'],
      rating: 4.5,
      reviewCount: 300,
      deliveryTimeMinutes: '25-35',
      deliveryFee: 3.5,
      isOpen: false,
    },
    {
      id: 'r3',
      name: 'Sweet Boutique',
      imageUrl: '/src/assets/images/restaurant-3.jpg',
      logoUrl: '/src/assets/images/logo-3.jpg',
      cuisineTags: ['Desserts', 'Bakery', 'Coffee'],
      rating: 4.9,
      reviewCount: 1000,
      deliveryTimeMinutes: '15-25',
      deliveryFee: 'free',
      isOpen: true,
      discountPercent: 15,
    },
    {
      id: 'r4',
      name: 'Pizza Palace',
      imageUrl: '/src/assets/images/restaurant-1.jpg',
      logoUrl: '/src/assets/images/logo-1.jpg',
      cuisineTags: ['Italian', 'Pizza'],
      rating: 4.6,
      reviewCount: 820,
      deliveryTimeMinutes: '30-40',
      deliveryFee: 1.99,
      isOpen: true,
    },
    {
      id: 'r5',
      name: 'Green Basket Market',
      imageUrl: '/src/assets/images/restaurant-2.jpg',
      logoUrl: '/src/assets/images/logo-2.jpg',
      cuisineTags: ['Groceries', 'Organic'],
      rating: 4.3,
      reviewCount: 210,
      deliveryTimeMinutes: '40-50',
      deliveryFee: 'free',
      isOpen: true,
    },
    {
      id: 'r6',
      name: 'Cairo Coffee Roasters',
      imageUrl: '/src/assets/images/restaurant-3.jpg',
      logoUrl: '/src/assets/images/logo-3.jpg',
      cuisineTags: ['Coffee', 'Breakfast'],
      rating: 4.7,
      reviewCount: 640,
      deliveryTimeMinutes: '15-20',
      deliveryFee: 2.5,
      isOpen: false,
    },
    {
      id: 'r7',
      name: 'The Grill House',
      imageUrl: '/src/assets/images/restaurant-1.jpg',
      logoUrl: '/src/assets/images/logo-1.jpg',
      cuisineTags: ['Grill', 'Meat', 'BBQ'],
      rating: 4.4,
      reviewCount: 390,
      deliveryTimeMinutes: '35-45',
      deliveryFee: 4.0,
      isOpen: true,
      discountPercent: 10,
    },
    {
      id: 'r8',
      name: 'Salad Days',
      imageUrl: '/src/assets/images/restaurant-2.jpg',
      logoUrl: '/src/assets/images/logo-2.jpg',
      cuisineTags: ['Healthy', 'Vegan'],
      rating: 4.8,
      reviewCount: 155,
      deliveryTimeMinutes: '20-25',
      deliveryFee: 2.0,
      isOpen: true,
    },
    {
      id: 'r9',
      name: 'Nile Bakery',
      imageUrl: '/src/assets/images/restaurant-3.jpg',
      logoUrl: '/src/assets/images/logo-3.jpg',
      cuisineTags: ['Bakery', 'Pastries'],
      rating: 4.2,
      reviewCount: 98,
      deliveryTimeMinutes: '25-30',
      deliveryFee: 'free',
      isOpen: true,
    },
  ];
}